### ISSUE TITLE
Clear node_modules on site start

### ISSUE THREAD

**Issue by josiahsprague** [solidusjs/vagrant-solidus#10]
While developing Solidus sites dependencies are often added/removed or moved back and forth between the `dependencies` and `devDependencies` fields. This leads frequently problems with dependencies missing from package.json when a site is deployed because they were installed locally at one point, so the site builds fine locally even though package.json is incorrect.

While it's easy enough to do `rm -rf node_modules` or `npm prune` to make sure that installed packages match package.json, doing so is mental overhead and easy to forget in the process of rapidly iterating on sites. I propose that we add `rm -rf node_modules` to the `vagrant site start` command before `npm install`.

Starting with a fresh `node_modules` directory every time a site is started is a good way to avoid this kind of oversight from happening.

**Comment by joanniclaborde** [comment]
`rm -rf node_modules` seems a bit overkill, starting a site will always take forever. How about a less agressive `npm prune` instead?

**Comment by josiahsprague** [comment]
There is always `-f` for faster startups. `npm prune` would probably work, but maybe we should do `npm prune && npm update` to make sure that all of the installed modules match the versions in package.json too.

**Comment by localjo** [comment]
Closing this since we're focusing on docker-solidus now.
